version: '3.8'

services:
  shop:
    image: dockware/play:6.5.7.0
    container_name: innovate3d-shop
    ports:
      - "22222:80"
    environment:
      - SHOPWARE_ADMIN=admin
      - SHOPWARE_PASSWORD=shopware
      - XDEBUG_ENABLED=0
    restart: always

  mysql:
    image: mysql:8.0
    container_name: innovate3d-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shopware
      - MYSQL_USER=shopware
      - MYSQL_PASSWORD=shopware
    ports:
      - "22226:3306"    # MySQL
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - shopware-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

networks:
  shopware-network:
    driver: bridge 